### ISSUE TITLE
QR code reader not working

### ISSUE THREAD

**Issue by tuberculo** [estevaocm/bitkey#11]
QR code app is not working for me. I can see that the camera is on, but no image is shown in the screen.

**Comment by estevaocm** [comment]
Hello, can you tell me which release you are using? Are both Electrum and QtQR failing? If you are using the latest release and all of them fail, it might be that your webcam is not supported, so we'd have to investigate and maybe patch the build.

**Comment by estevaocm** [comment]
Please try https://github.com/estevaocm/bitkey/releases/latest if you haven't already.

**Comment by tuberculo** [comment]
I was using a version that I built myself from your repo two days ago. I only tested QtQR, I forgot to test Electrum. I'll try Electrum later.

**Comment by estevaocm** [comment]
Well, in any case, QtQR should have worked. Webcam support is enabled by the package "cheese". It has worked in my VM on my desktop with a USB cam and also booting my laptop with the built-in cam. Maybe cheese doesn't work with your cam?

**Comment by tuberculo** [comment]
Camera is working in Electrum. 
The issue is only in QtQR. It asks for permission to use the camera, (and I can see that the camera is on) but it shows no image.

**Comment by estevaocm** [comment]
That's strange. But I must confess this has been a trial-and-error experience for me, I'm not an expert. Installing cheese solved everything for me in my VM and laptop, as I explained. I don't really like QtQR very much because even when it works it keeps capturing even after decoding. Very unintuitive. But it was the only usable GUI I found so far.

**Comment by estevaocm** [comment]
Also note that zbar-tools is installed, you might be able to use that as well.

**Comment by estevaocm** [comment]
@tuberculo, can we get some more information on the error you got?

**Comment by tuberculo** [comment]
What do you want to know?

**Comment by estevaocm** [comment]
Camera specs would be useful. Is it a laptop cam or independent USB cam? Can you test different devices on the same PC?

Recapping, the camera works with Electrum but no QtQR, right? Can you test with zbar-tools? Or enter hot-online mode and test at https://webqr.com ?

With more information we can investigate why it's not working with your device and improve cam support.

**Comment by tuberculo** [comment]
It's a laptop cam. 
I'm confused about the software names, maybe I informed it wrong here. I can't find QtQR or zbar-tools in BitKey. 
The issue I reported occurs when I open "qrcode scanner". I can see now that it is an offline version of webqr.com. Maybe the problem is in it. The camera turns on, but no image is shown. The frame where the image was supposed to appear seems different. It is bigger than usual and remains all white. But, the website webqr.com works fine in online mode. So, I think the problem is specific to "qrcode scanner" app.

**Comment by estevaocm** [comment]
Oh, that's right. Now it all makes sense. That web QR scanner will not work because of a security block from browsers. They are only allowed to use the webcam when hosted in a web server, not when running from the filesystem. If you use one of the newer releases you will find the QtQR scanner which works. Thank you for clarifying.
