### ISSUE TITLE
Great fork! Adding CryptoSeed github project 

### ISSUE THREAD

**Issue by zanderisrael** [estevaocm/bitkey#24]
Hey, 

I have my own version of bitkey, not published tho. 
In my version I have added CryptoSeed:
https://github.com/anderson-arlen/cryptoseed

Are you willing to add this to your fork? I want to use your fork in order to have a segwit enabled address.

**Comment by zanderisrael** [comment]
If you cant ill try and push a commit of my own if thats ok? 
BTW not patching electrum is a bit sketchy...

**Comment by estevaocm** [comment]
Sure, I can probably add that soon.

Why would you need to patch Electrum? It works fine straight out of Github.

**Comment by zanderisrael** [comment]
Well from what I can figure out the patch makes sure that unnecessary functions are disabled when in cold online. 
so you don't leak your keys when in cold online.

**Comment by estevaocm** [comment]
I believe you are mistaken. Let's take a look at https://github.com/bitkey/bitkey/blob/master/overlay/usr/local/src/electrum.patch

First they only remove the check for an existing wallet, since the wrapper in Bitkey creates the wallet beforehand.

Then there is code for the deseeded wallet for cold-online mode, but this function no longer exists so cold-online mode was disabled.

Then we have a bit of a bugfix which no longer applies.

Then there have been removed some options for creating wallets. I don't think this is necessary and can be undesirable for advanced users.

Finally, a warning about being offline is disabled.

So I don't see how any of that contributes to security. The system should have all networking disabled regardless.

**Comment by estevaocm** [comment]
Added CryptoSeed
